name: tags

on:
  push:
    branches:
      - main
    paths:
      - tags/**
  pull_request:
    branches:
      - main
    paths:
      - tags/**
  workflow_dispatch:
    inputs:
      checkflag:
        description: 'If true, validate the changes. If false, apply the changes'
        required: true
        default: 'true'
      environments:
        description: 'run against given environments.  Space separated, e.g. NOMSDevTestEnvironments'
        required: true
        default: 'NOMSDevTestEnvironments'

jobs:
  # This workflow can be triggered multiple ways,
  # e.g. manually or by push/pull request.
  # The first job figures out the parameters based on trigger type.
  # The second job runs ansible for each environment
  prepare-tags:
    runs-on:
      - ubuntu-latest
    outputs:
      apply_tags: ${{ steps.parseinput.outputs.apply_tags }}
      aztagscli_args: ${{ steps.setupargs.outputs.aztagscli_args }}
      env_matrix: ${{ steps.setupenv.outputs.env_matrix }}
    steps:
      - name: Clone repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1


      # since this is a public repo, use specific version of this action
      # to ensure it can't be used to steal secrets
      - name: Get list of committed files
        id: files
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42 # v1
        with:
          format: 'space-delimited'

      - name: Figure out updated environments
        id: envs
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          echo "Updated files: ${{ steps.files.outputs.all }}"
          envs=
          for file in ${{ steps.files.outputs.all }}; do
              dir=$(dirname $file)
              envs=$(echo "$envs"; echo $dir | egrep -o '^tags/[^\/]+/[^\/]+' | cut -d\/ -f2,3)
          done
          envs=$(echo "$envs" | sort -u | grep -v -e '^$' || true)
          echo List of environments [${envs}]
          echo ::set-output name=envs::${envs}

      - name: Parse inputs
        id: parseinput
        run: |
          echo "Parsing input parameters event=${GITHUB_EVENT_NAME}"
          branch=$(echo ${GITHUB_REF##*/})
          echo "Extracted last part of branch [${branch}] from ${GITHUB_REF}"
          # figure out which environment to deploy to and whether to set checkflag or not
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            # manual trigger - take params from inputs
            checkflag="${{ github.event.inputs.checkflag }}"
            environments="${{ github.event.inputs.environments }}"
          elif [[ "${GITHUB_EVENT_NAME}" == "push" && ( "${branch}" == "master" || "${branch}" == "main" ) ]]; then
            # push to master/main - deploy for real
            checkflag="false"
            environments="${{ steps.envs.outputs.envs }}"
          else
            # any other push - deploy with check flag set
            checkflag="true"
            environments="${{ steps.envs.outputs.envs }}"
          fi
          [[ -z ${environments} ]] && apply_tags='false' || apply_tags='true'
          echo "::set-output name=apply_tags::${apply_tags}"
          echo "::set-output name=environments::${environments}"
          echo "::set-output name=checkflag::${checkflag}"

      - name: Setup aztagscli cmdline args
        id: setupargs
        env:
          checkflag: ${{ steps.parseinput.outputs.checkflag }}
        run: |
          echo "Set aztagscli cmdline args [checkflag=${checkflag}]"
          # Don't update resource groups.  This way we can just use
          # a tag contributor SP. Resources with the "source_code"
          # tag will be skipped.
          args="--minscope 5 --skiptags source_code -a -y"
          # add dryrun if checkflag is set
          if [[ "${checkflag}" != "false" ]]; then
            args="${args} -d"
          fi
          echo "::set-output name=aztagscli_args::${args}"

      - name: Setup environment matrix
        id: setupenv
        env:
          environments: ${{ steps.parseinput.outputs.environments }}
        run: |
          echo "Setup ansible actions for environments [${environments}]"
          # create JSON that will feed into a strategy matrix
          echo -n "::set-output name=env_matrix::{\"include\":["
          delimiter=""
          for env in ${environments}; do
            echo -n "${delimiter}"
            echo -n '{"environment":"'${env}'"}'
            delimiter=","
          done
          echo "]}"

  apply-tags:
    # Iterate through each environment and trigger the generic
    # ansible-playbook repository dispatch workflow
    needs: prepare-tags
    if: ${{ needs.prepare-tags.outputs.apply_tags == 'true' }}
    strategy:
      matrix: ${{ fromJson(needs.prepare-tags.outputs.env_matrix) }}
      fail-fast: false
    runs-on:
      - ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1


      - name: Azure Login
        uses: azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
        with:
          creds: ${{secrets.DSO_INFRA_AZURE_TAGS}}

      - name: Install dependencies
        run: |
          pip3 install -r src/requirements.txt

      - name: Check or apply tags
        run: |
          cd tags
          echo ./aztagscli-helper.sh ${{ matrix.environment }} ${{ needs.prepare-tags.outputs.aztagscli_args }}
          ./aztagscli-helper.sh ${{ matrix.environment }} ${{ needs.prepare-tags.outputs.aztagscli_args }}
